In [1]:
print("Aashish got that done !!")

Aashish got that done !!


In [2]:
import numpy as np
import pandas as pd

In [4]:
x = np.array([[1,2,3],[4,5,6]])

In [6]:
print('x:\n{}'.format(x))

x:
[[1 2 3]
 [4 5 6]]


In [7]:
from scipy import sparse

In [8]:
eye = np.eye(4)

In [10]:
print("Numpy Matrix:\n{}".format(eye))

Numpy Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
sparse_ = sparse.csr_matrix(eye)
print("Sparse Matrix:\n{}".format(sparse_))

Sparse Matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
